apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: metrics
  source:
    repoURL: https://github.com/mertyldrm/k8s-manifests.git
    targetRevision: HEAD
    path: tenable-exporter
  destination:
    server: https://1A6FFDF39C4C5C6BFECC3DA1CF49AB9C.gr7.us-east-1.eks.amazonaws.com
    namespace: default