apiVersion: v1
kind: Service
metadata:
  name: prometheus-headless-service
  namespace: monitoring
spec:
  ports:
  - port: 8080
  clusterIP: None
  selector:
    app: prometheus-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-deployment
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  volumeClaimTemplates: 
  - metadata:
      name: prometheus-storage-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:  
        requests:
          storage: 10Gi

  serviceName: "prometheus-headless-service"
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      serviceAccountName: prometheus
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 65533
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.enable-lifecycle"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 2
              memory: 4Gi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
              
            - name: prometheus-storage-volume
              mountPath: /prometheus/
            
            - name: prometheus-alert-volume
              mountPath: /etc/alert
          
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090

        - name: prometheus-watcher
          image: weaveworks/watch
          imagePullPolicy: IfNotPresent
          args: ["-v", "-t", "-p=/etc/prometheus", "curl", "-X", "POST","--fail", "-o", "-", "-sS", "http://localhost:9090/-/reload"]
          volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus/

        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.6.0
          args:
            - --repo=https://github.com/mertyldrm/prometheus-alerts
            - --branch=main
            - --depth=1
            - --root=/etc/prometheus
            - --webhook-url=http://localhost:9090/-/reload

          volumeMounts:
          - name: prometheus-alert-volume
            mountPath: /etc/prometheus
            readOnly: false

          securityContext:
            runAsUser: 65533

      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf

        - name: prometheus-alert-volume
          emptyDir: {}  